networks:
  app:
    name: app
    driver: bridge
    external: true

services:
  strapi:
    container_name: strapi-app
    build:
      context: .
      dockerfile: Dockerfile
    image: strapi-app:latest
    restart: unless-stopped
    networks:          # <--- AGREGA ESTO
      - app            # <--- AGREGA ESTO
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./.tmp:/opt/app/.tmp
      - ./public/uploads:/opt/app/public/uploads
